[package]
name = "allocated"
version = "0.1.2"
edition = "2021"
authors = ["Alex Chamberlain"]
description = "Abstractions for working with explicitly allocated data structures"
license = "MIT OR Apache-2.0"
repository = "https://github.com/alexchamberlain/allocated-rs"
readme = "README.md"
keywords = ["allocator", "data-structures", "allocation"]
categories = ["data-structures", "memory-management", "no-std"]

[dependencies]
allocator-api2 = { version = "0.4.0", default-features = false, features = ["alloc"] }

[features]
default = ["std"]
std = ["allocator-api2/std"]

[lints.clippy]
undocumented_unsafe_blocks = "warn"
multiple_unsafe_ops_per_block = "warn"
